export const HoneymoonCategories = {
  India: [
    "Goa",
    "Kerala",
    "Shimla",
    "Manali",
    "Andaman",
    "Himachal",
    "Kodaikanal",
    "Coorg",
    "Ooty",
    "Kashmir",
    "Darjeeling",
  ],
  International: [
    "Maldives",
    "Bali",
    "Mauritius",
    "Phuket",
    "Switzerland",
    "Seychelles",
    "Langkawi",
    "Paris",
    "Italy",
    "Krabi",
    "Greece",
    "Thailand",
    "Dubai",
    "Sri Lanka",
    "Singapore",
    "Malaysia",
    "Croatia",
    "South Africa",
    "Koh Samui",
    "Australia",
    "Spain",
    "Europe",
  ],
};
