// destinationData.ts
export const PackageCategories = {
  Africa: [
    "Kenya",
    "Morocco",
    "Seychelles",
    "South Africa",
    "Zimbabwe",
    "Tanzania",
  ],
  America: ["Alaska", "South America", "Central America", "USA", "Canada"],
  Pacific: ["Australia", "Fiji", "New Zealand"],
  Asia: [
    "Bali",
    "Cambodia",
    "China",
    "Hong Kong",
    "Japan",
    "Indonesia",
    "Kazakhstan",
    "Russia",
    "South Korea",
    "Malaysia",
    "Singapore",
    "Philippines",
    "Taiwan",
    "Thailand",
    "Vietnam",
    "Uzbekistan",
  ],
  Europe: [
    "Austria",
    "Belgium",
    "Bulgaria",
    "Croatia",
    "Czech Republic",
    "Denmark Republic",
    "Finland Republic",
    "France",
    "Germany",
    "Greece",
    "Greenland",
    "Hungary",
    "Iceland",
    "Ireland",
    "Italy",
    "London",
    "Netherlands",
    "Norway",
    "Portugal",
    "Romania",
    "Russia",
    "Slovakia",
    "Spain",
    "Sweden",
    "Switzerland",
    "Turkey",
    "United Kingdom",
  ],
  Island: ["Madagascar", "Maldives", "Mauritius", "Reunion", "Sri Lanka"],
  MiddleEast: ["Israel", "Jordan", "Oman", "Qatar", "UAE", "Dubai", "Egypt"],
  Cruises: ["Cordelia Cruises"],
};
